version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: apicurio-registry
      POSTGRES_PASSWORD: password
  tenant-manager:
    image: apicurio/apicurio-tenant-manager-api:latest
    ports:
      - "8081:8585"
    environment:
      DATASOURCE_URL: 'jdbc:postgresql://postgres/apicurio-registry'
      DATASOURCE_USERNAME: apicurio-registry
      DATASOURCE_PASSWORD: password
      REGISTRY_ROUTE_URL: 'http://registry-app:8080'
    depends_on:
      - postgres
      - registry-app
  registry-app:
    image: apicurio/apicurio-registry-sql:latest
    ports:
      - "8080:8080"
    environment:
      REGISTRY_DATASOURCE_URL: 'jdbc:postgresql://postgres/apicurio-registry'
      REGISTRY_DATASOURCE_USERNAME: apicurio-registry
      REGISTRY_DATASOURCE_PASSWORD: password